Repository UMC-FITple/Backend, pull requests merged in 2024-08, with the labels that each got.

#18 로그인 기능 완료
  package-lock.json
  package.json
  src/config/response.status.js
  src/domains/login/login.controller.js
  src/domains/login/login.dao.js
  src/domains/login/login.dto.js
  src/domains/login/login.provider.js
  src/domains/login/login.service.js
  src/domains/login/login.sql.js
  src/index.js
  src/middlewares/logincheck.js
  src/routes/login.js
  src/swagger/login.swagger.yaml
Labels: :sparkles: feat

#21 통합 검색 조회 기능
  package-lock.json
  src/config/db.config.js
  src/domains/search/search.controller.js
  src/domains/search/search.dao.js
  src/domains/search/search.dto.js
  src/domains/search/search.provider.js
  src/domains/search/search.service.js
  src/domains/search/search.sql.js
  src/index.js
  src/routes/search.js
  src/swagger/search.swagger.yaml
  src/swagger/swagger.config.js
Labels: :sparkles: feat

#22 사이즈 이미지표 업로드
  package.json
  pnpm-lock.yaml
  private/uploads/1723180160809-무신사1.png
  private/uploads/1723180165246-무신사1.png
  private/uploads/1723180185135-무신사1.png
  private/uploads/1723180197525-무신사1.png
  private/uploads/1723180198725-무신사1.png
  private/uploads/1723180200048-무신사1.png
  private/uploads/1723180490374-무신사1.png
  private/uploads/1723180632184-무신사1.png
  private/uploads/1723181125376-무신사1.png
  src/domains/size/uploadsize/uploadsize.controller.js
  src/domains/size/uploadsize/uploadsize.dao.js
  src/domains/size/uploadsize/uploadsize.dto.js
  src/domains/size/uploadsize/uploadsize.service.js
  src/domains/size/uploadsize/uploadsize.sql.js
  src/index.js
  src/routes/uploadsize.routes.js
  src/swagger/swagger.config.js
  src/swagger/uploadsize.swagger.yaml
Labels: :bug: fix, :test_tube: test, :sparkles: feat

#24 스웨거 에러 해결
  package-lock.json
  src/index.js
  src/swagger/login.swagger.yaml
  src/swagger/signup.swagger.yaml
  src/swagger/swagger.config.js
Labels: :bug: fix

#32 CI/CD 파이프라인 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#36 CI/CD 파이프라인 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#38 CI/CD 파이프라인 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#40 CI/CD 파이프라인 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#42 CI/CD 파이프라인 수정
  .github/workflows/dev_deploy.yml
Labels: :bug: fix

#44 CI/CD 파이프라인 수정-8
  Procfile
  index.js
  src/swagger/swagger.config.js
Labels: :sparkles: feat

#46 CI/CD 파이프라인 수정-9
  .github/workflows/dev_deploy.yml
Labels: :takeout_box: chore

#48 CI/CD 파이프라인 수정-10
  .github/workflows/dev_deploy.yml
Labels: :takeout_box: chore

#27 아이디 찾기 및 비밀번호 재설정 기능 완료
  src/config/response.status.js
  src/domains/auth/auth.controller.js
  src/domains/auth/auth.dao.js
  src/domains/auth/auth.service.js
  src/index.js
  src/routes/auth.js
  src/swagger/findId.swagger.yaml
  src/swagger/resetPassword.swagger.yaml
Labels: :sparkles: feat

#51 CI/CD 파이프라인 수정-11
  package.json
  pnpm-lock.yaml
  webpack.config.cjs
Labels: :takeout_box: chore

#53 CI/CD 파이프라인 수정-12
  .github/workflows/dev_deploy.yml
Labels: :takeout_box: chore

#55 CI/CD 파이프라인 수정-13
  package.json
  webpack.config.cjs
  webpack.config.js
Labels: :takeout_box: chore

#58 CI/CD 파이프라인 수정-14
  .platform/nginx/nginx.conf
  index.js
  src/swagger/swagger.config.js
Labels: :takeout_box: chore

#49 로그인 유저 옷장 조회 로직 구현
  package-lock.json
  package.json
  src/config/db.config.js
  src/config/response.status.js
  src/domains/closet/closet.controller.js
  src/domains/closet/closet.dao.js
  src/domains/closet/closet.dto.js
  src/domains/closet/closet.provider.js
  src/domains/closet/closet.service.js
  src/domains/closet/closet.sql.js
  src/domains/login/login.controller.js
  src/domains/login/login.dto.js
  src/domains/login/login.provider.js
  src/domains/login/login.sql.js
  src/index.js
  src/routes/closet.js
  src/swagger/closet.swagger.yaml
  src/swagger/login.swagger.yaml
  src/swagger/uploadsize.swagger.yaml
Labels: :sparkles: feat

#62 response status 재설정
  src/domains/auth/auth.controller.js
  src/domains/login/login.controller.js
  src/domains/refreshToken/refreshToken.controller.js
  src/domains/signup/signup.controller.js
  src/middlewares/logincheck.js
Labels: :bug: fix

#64 임시 토큰 발급
  src/index.js
  src/routes/temp-token.js
Labels: :sparkles: feat

#66 임시 토큰 발행시 쿠키 생성
  src/routes/temp-token.js
Labels: :bug: fix

#70 사이즈 수기 등록 CRUD
  private/uploads/1724167953617-무신사위캔더스반팔.png
  private/uploads/1724167956510-무신사위캔더스반팔.png
  src/domains/comparesize/comparesize.controller.js
  src/domains/comparesize/comparesize.dao.js
  src/domains/comparesize/comparesize.dto.js
  src/domains/comparesize/comparesize.service.js
  src/index.js
  src/routes/comparesize.routes.js
  src/swagger/comparesize.swagger.yaml
  src/swagger/uploadsize.swagger.yaml
Labels: :bug: fix, :memo: docs, :test_tube: test, :sparkles: feat, :takeout_box: chore

#60 내 프로필 설정 기능 완료
  package-lock.json
  package.json
  src/config/response.status.js
  src/config/s3.config.js
  src/db/index.js
  src/db/models/body_info.js
  src/db/models/member.js
  src/db/models/perfer_fit.js
  src/db/models/style.js
  src/db/models/user_fit.js
  src/db/models/user_style.js
  src/domains/auth/auth.controller.js
  src/domains/auth/auth.dao.js
  src/domains/auth/auth.service.js
  src/domains/myprofile/myprofile.controller.js
  src/domains/myprofile/myprofile.dao.js
  src/domains/myprofile/myprofile.service.js
  src/domains/signup/signup.controller.js
  src/domains/signup/signup.dao.js
  src/domains/signup/signup.service.js
  src/index.js
  src/routes/myprofile.js
  src/swagger/findId.swagger.yaml
  src/swagger/myprofil.swagger.yaml
  src/swagger/resetPassword.swagger.yaml
Labels: :sparkles: feat

#73 검색 cursorId 수정
  src/domains/search/search.provider.js
  src/swagger/search.swagger.yaml
Labels: :bug: fix, :memo: docs

#75 검색 size 고정
  src/domains/search/search.dao.js
  src/domains/search/search.sql.js
Labels: :bug: fix, :memo: docs

#77 임시 토큰 로그인하도록 수정
  src/routes/temp-token.js
Labels: :bug: fix

#81 검색 결과 없을 시 문자열 반환
  src/config/response.status.js
  src/domains/search/search.dao.js
  src/domains/search/search.dto.js
Labels: :bug: fix

#83 옷장 직접 등록하기 로직 구현
  pnpm-lock.yaml
  src/config/response.status.js
  src/domains/closet/closet.controller.js
  src/domains/closet/closet.dao.js
  src/domains/closet/closet.dto.js
  src/domains/closet/closet.provider.js
  src/domains/closet/closet.service.js
  src/domains/closet/closet.sql.js
  src/routes/closet.js
  src/swagger/closet.swagger.yaml
Labels: :sparkles: feat

#89 통합검색 쿼리스트링 입력 시 사이즈 고정
  src/domains/search/search.sql.js
Labels: :bug: fix, :memo: docs

#90 브랜드 검색과 직접 등록하기 로직 구현
  src/domains/closet/closet.controller.js
  src/domains/closet/closet.dao.js
  src/domains/closet/closet.dto.js
  src/domains/closet/closet.provider.js
  src/domains/closet/closet.service.js
  src/domains/closet/closet.sql.js
  src/domains/search/search.dao.js
  src/domains/search/search.dto.js
  src/domains/search/search.provider.js
  src/domains/search/search.sql.js
  src/routes/closet.js
  src/swagger/closet.swagger.yaml
  src/swagger/search.swagger.yaml
Labels: :sparkles: feat

#92 통합검색 cloth_img 반환
  src/domains/search/search.sql.js
Labels: :memo: docs, :sparkles: feat

#94 데이터 부족한 검색결과 에러 처리
  src/domains/search/search.dao.js
  src/domains/search/search.dto.js
  src/domains/search/search.sql.js
Labels: :bug: fix

#99 옷장 페이징 삭제
  src/domains/closet/closet.dao.js
  src/domains/closet/closet.dto.js
  src/domains/closet/closet.provider.js
  src/domains/closet/closet.sql.js
  src/swagger/closet.swagger.yaml
Labels: :bug: fix

#101 옷장 검색 기능 구현
  src/domains/closet/closet.dao.js
  src/domains/closet/closet.provider.js
  src/domains/closet/closet.sql.js
  src/swagger/closet.swagger.yaml
Labels: :sparkles: feat

#107 프로필 상단 정보 조회 기능 구현
  src/domains/profile/profile.controller.js
  src/domains/profile/profile.dao.js
  src/domains/profile/profile.dto.js
  src/domains/profile/profile.provider.js
  src/domains/profile/profile.service.js
  src/domains/profile/profile.sql.js
  src/index.js
  src/routes/profile.js
  src/swagger/profile.swagger.yaml
Labels: :sparkles: feat

#110 좋아하는 옷 조회 기능 구현
  src/domains/profile/profile.controller.js
  src/domains/profile/profile.dao.js
  src/domains/profile/profile.dto.js
  src/domains/profile/profile.provider.js
  src/domains/profile/profile.sql.js
  src/routes/profile.js
  src/swagger/profile.swagger.yaml
Labels: :sparkles: feat

#112 관심있는 옷 조회 기능 구현
  src/domains/profile/profile.controller.js
  src/domains/profile/profile.dao.js
  src/domains/profile/profile.dto.js
  src/domains/profile/profile.provider.js
  src/domains/profile/profile.sql.js
  src/routes/profile.js
  src/swagger/profile.swagger.yaml
Labels: :sparkles: feat

#114 체형 정보 조회 기능 구현
  pnpm-lock.yaml
  src/domains/profile/profile.controller.js
  src/domains/profile/profile.dao.js
  src/domains/profile/profile.dto.js
  src/domains/profile/profile.provider.js
  src/domains/profile/profile.sql.js
  src/routes/profile.js
  src/swagger/profile.swagger.yaml
Labels: :sparkles: feat

#116 더보기 기본 정보 조회 기능 구현
  src/domains/profile/profile.controller.js
  src/domains/profile/profile.dao.js
  src/domains/profile/profile.dto.js
  src/domains/profile/profile.provider.js
  src/domains/profile/profile.sql.js
  src/routes/profile.js
  src/swagger/profile.swagger.yaml
Labels: :sparkles: feat
